name: Build operations
on:
  push:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test section'
      - name: get repository
        uses: actions/checkout@v3
      - run: ls -al