name: Build operations
on:
  push:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test section'
      - name: get repository
        uses: actions/checkout@v3
      - run: ls -al

      # Install Python
      - name: Configure Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Run Test
      - run: pip install pytest
      - run: pytest -v

      # Publish to Mqtt
      - name: Introduction to Mqtt
        uses: juhrlass/mqtt-action@master
        with:
          protocol: mqtt
          host:  broker.hivemq.com
          port: 1883
          topic: "OCDdevops"
          message: "${{ github.actor }} Build successful" 
          username: ""
          password: ""
