name: Build operations
on:
  push:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test section'
      - name: get repository
        uses: actions/checkout@v3
      - run: ls -al
      - name: Configure Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pytest
      - run: pytest
